version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: dad-react-app:latest
    container_name: dad-react-app
    env_file:
      - .env
    ports:
      - "3001:80"
    restart: unless-stopped
